plugins {
    id "com.android.application"
}

android {
    namespace "com.soundbox.aiclient"
    compileSdk 35

    defaultConfig {
        applicationId "com.soundbox.aiclient"
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
        debug {
            applicationIdSuffix ".debug"
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
